version: "3"

services:
  backend:
    build: ./cskinstore-backend
    container_name: cskinstore-backend
    restart: always
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/cskinstore
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: cskinstore-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
